# -- 코드를 입력하세요
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM (SELECT *
     FROM REST_INFO
     ORDER BY FAVORITES DESC
     LIMIT 18446744073709551615) RI
GROUP BY RI.FOOD_TYPE
ORDER BY RI.FOOD_TYPE DESC
