-- 코드를 입력하세요
SELECT 
YEAR(os.SALES_DATE) AS YEAR, 
MONTH(os.SALES_DATE) AS MONTH, 
ui.GENDER AS GENDER,
COUNT(DISTINCT os.USER_ID) AS USERS
FROM USER_INFO ui JOIN ONLINE_SALE os ON ui.USER_ID = os.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY SUBSTR(os.SALES_DATE, 1, 7), ui.GENDER
ORDER BY YEAR, MONTH, GENDER