-- 코드를 입력하세요
SELECT fp.PRODUCT_ID, PRODUCT_NAME, (SUM(AMOUNT)*fp.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT fp INNER JOIN FOOD_ORDER fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE SUBSTR(PRODUCE_DATE, 1, 7) = '2022-05'
GROUP BY fp.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;