-- 코드를 입력하세요
SELECT b.CATEGORY CATEGORY, SUM(bs.SALES) TOTAL_SALES
FROM BOOK b JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE SUBSTR(bs.SALES_DATE, 1, 7) = '2022-01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY
